/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import static model.Main.nivel;

/**
 *
 * @author 821223909
 */
public class Intro extends javax.swing.JFrame {

    /**
     * Creates new form Intro
     */
   
    public Intro() {
        // Configurar o título e outras propriedades da janela
        setTitle("Intro");
        setSize(400, 300); // Defina o tamanho da janela
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Defina a localização da janela no centro da tela
        setLocationRelativeTo(null);

        // Tornar a janela visível
        setVisible(true);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_text = new javax.swing.JLabel();
        btn_selectLevel = new javax.swing.JButton();
        btn_results = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titulo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("Orientações Iniciais");

        lbl_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text.setText("<html>\n<h2 style=\"text-align: center;\">Nível I</h2> \n<p style=\"text-align: center;\"> Este nível destina-se a iniciantes e contém questões de matemática básica, como adição e subtração simples. As questões podem envolver números pequenos e operações diretas.</p>  \n<h2 style=\"text-align: center;\">Nível II</h2> \n<p style=\"text-align: center;\">Este nível oferece questões com um grau um pouco maior de dificuldade. Pode incluir adição e subtração de números maiores, além de introduzir questões de multiplicação e divisão simples.</p>\n<h2 style=\"text-align: center;\">Nível III</h2> \n<p style=\"text-align: center;\">Neste nível, as questões se tornam mais complexas. Elas podem incluir números maiores, operações com frações e mais variações de questões de multiplicação e divisão. </p>  \n<h2 style=\"text-align: center;\">Nível IV</h2> \n<p style=\"text-align: center;\">O nível mais alto de dificuldade, projetado para desafiar até mesmo os alunos mais avançados. As questões podem envolver operações matemáticas complexas, como multiplicação e divisão de números com casas decimais, frações e problemas matemáticos mais elaborados.</p>\n</html>");

        btn_selectLevel.setText("Selecionar o Nível");
        btn_selectLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectLevelActionPerformed(evt);
            }
        });

        btn_results.setText("Resultados Anteriores");
        btn_results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_results, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_selectLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_text, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_text, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_selectLevel)
                    .addComponent(btn_results))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_selectLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectLevelActionPerformed
        model.Main.nivel();
    }//GEN-LAST:event_btn_selectLevelActionPerformed

    private void btn_resultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultsActionPerformed
        model.Main.resultado();
    }//GEN-LAST:event_btn_resultsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_results;
    private javax.swing.JButton btn_selectLevel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_text;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
