/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Pontuacao;
import java.util.List;
import javax.swing.JFrame;
import static model.Main.questoes;
import model.Pontos;

/**
 *
 * @author Wesley
 */
public final class Nivel extends javax.swing.JFrame {

    /**
     * Creates new form Niveis
     */
    
    public Nivel() {
        // Configurar o título e outras propriedades da janela
        setTitle("Nivel");
        setSize(400, 300); // Defina o tamanho da janela
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Defina a localização da janela no centro da tela
        setLocationRelativeTo(null);

        // Tornar a janela visível
        setVisible(true);
        
        initComponents();
        
        checkNivel();
        
    }
    
    public void checkNivel(){
        
        btn_nivel2.setEnabled(false);
        btn_nivel3.setEnabled(false);
        btn_nivel4.setEnabled(false);
        
        List<model.Pontos> resultados = Pontuacao.getPontuacao();
        int sizeLista = resultados.size();
        
        for(int i = 0; i < sizeLista; i++){
            Pontos result = resultados.get(i);
            
            if (result.getNivel() == 1) btn_nivel2.setEnabled(true);
            if (result.getNivel() == 2) btn_nivel3.setEnabled(true);
            if (result.getNivel() == 3) btn_nivel4.setEnabled(true);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_nivel1 = new javax.swing.JButton();
        btn_nivel2 = new javax.swing.JButton();
        btn_nivel3 = new javax.swing.JButton();
        btn_nivel4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione o Nível");

        btn_nivel1.setText("Nível I");
        btn_nivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nivel1ActionPerformed(evt);
            }
        });

        btn_nivel2.setText("Nível II");
        btn_nivel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nivel2ActionPerformed(evt);
            }
        });

        btn_nivel3.setText("Nível III");
        btn_nivel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nivel3ActionPerformed(evt);
            }
        });

        btn_nivel4.setText("Nível IV");
        btn_nivel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nivel4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_nivel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nivel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_nivel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_nivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_nivel1)
                .addGap(26, 26, 26)
                .addComponent(btn_nivel2)
                .addGap(26, 26, 26)
                .addComponent(btn_nivel3)
                .addGap(26, 26, 26)
                .addComponent(btn_nivel4)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nivel1ActionPerformed
        questoes(1);
    }//GEN-LAST:event_btn_nivel1ActionPerformed

    private void btn_nivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nivel2ActionPerformed
        questoes(2);
    }//GEN-LAST:event_btn_nivel2ActionPerformed

    private void btn_nivel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nivel3ActionPerformed
        questoes(3);
    }//GEN-LAST:event_btn_nivel3ActionPerformed

    private void btn_nivel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nivel4ActionPerformed
        questoes(4);
    }//GEN-LAST:event_btn_nivel4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_nivel1;
    private javax.swing.JButton btn_nivel2;
    private javax.swing.JButton btn_nivel3;
    private javax.swing.JButton btn_nivel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
