/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;
import controller.Perguntas;
import controller.Pontuacao;
import java.util.ArrayList;
import java.util.List;
import model.Main;

/**
 *
 * @author Wesley
 */
public class Questionario extends javax.swing.JFrame {
    
    private int pontuacao;
    private int resposta;
    private int pontos;
    private int nivel;
    private int next = 0;
    private List<model.Questoes> perguntas = new ArrayList<>();
    private model.Questoes questao = new model.Questoes();
    private List<Integer> idQuestao = new ArrayList<>();
    private List<Integer> idPontos = new ArrayList<>();
    

    /**
     * Creates new form Questoes
     */
    public Questionario(int nivel) {
        
        this.nivel = nivel;
        //Carregar as 10 perguntas do banco de dados.
        
        // Configurar o título e outras propriedades da janela
        setTitle("Questionário");
        setSize(600, 300); // Defina o tamanho da janela
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Defina a localização da janela no centro da tela
        setLocationRelativeTo(null);

        // Tornar a janela visível
        setVisible(true);
        
        initComponents();
        
        pontuacao = 0;
        pontos = 10;
        Alternativas.clearSelection();
        
        exibePrimeiraQuestao();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alternativas = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        txt_titulo = new javax.swing.JLabel();
        txt_numero = new javax.swing.JLabel();
        txt_questao = new javax.swing.JLabel();
        rbt_a = new javax.swing.JRadioButton();
        rbt_b = new javax.swing.JRadioButton();
        rbt_c = new javax.swing.JRadioButton();
        rbt_d = new javax.swing.JRadioButton();
        rbt_e = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_dica = new javax.swing.JLabel();
        btn_confirmar = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_titulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_titulo.setText("Titulo");

        txt_numero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_numero.setText("Numero");

        txt_questao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_questao.setText("Enunciado da questão");

        Alternativas.add(rbt_a);
        rbt_a.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbt_a.setText("A");

        Alternativas.add(rbt_b);
        rbt_b.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbt_b.setText("B");

        Alternativas.add(rbt_c);
        rbt_c.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbt_c.setText("C");

        Alternativas.add(rbt_d);
        rbt_d.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbt_d.setText("D");

        Alternativas.add(rbt_e);
        rbt_e.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbt_e.setText("E");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("a)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("c)");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("e)");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("d)");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("b)");

        txt_dica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_dica.setForeground(new java.awt.Color(0, 153, 255));

        btn_confirmar.setText("Confirmar");
        btn_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_questao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbt_d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(69, 69, 69))
                            .addComponent(rbt_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbt_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbt_e)
                            .addComponent(rbt_a))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_dica, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(btn_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_numero, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(txt_questao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_dica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_confirmar)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbt_a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbt_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbt_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbt_d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbt_e, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addGap(108, 108, 108))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmarActionPerformed
        //Verifica se a resposta está correta:
        if(resposta == verificaResposta()){
            //Grava a questão e pontos da questão 
            idQuestao.add(questao.getId());
            idPontos.add(pontos);

            // Adiciona Pontuação 
            pontuacao += pontos;
            pontos = 10;
            
            // Próxima Pergunta:
            avancarParaProximaPergunta();
        } 
        else {
            pontos = (pontos == 0) ? 0 : pontos - 1;
            preencheDica();
        }
        Alternativas.clearSelection();

    }//GEN-LAST:event_btn_confirmarActionPerformed
    
    public void exibePrimeiraQuestao() {
        perguntas = Perguntas.getPerguntas(nivel);
        txt_titulo.setText("Questionário Nível - " + nivel);
        next = 0;
        
        preencherQuestao();
    }
    
    private void avancarParaProximaPergunta() {
        next++;
        if (next > 11) {
            Pontuacao.setPontuacao(pontuacao);
            Main.resultado();
        } 
        else{
            preencherQuestao();
        }
    }
    
    public void preencherQuestao(){
        //Preenche Questão:
        questao = perguntas.get(next);
        txt_numero.setText(String.valueOf(next + 1));
        txt_questao.setText("<html>" + questao.getPergunta() + "</html>");
        resposta = questao.getResposta();
        
        //Preenche as Alternativas:
        rbt_a.setText(String.valueOf(questao.alternativas.get(0)));
        rbt_b.setText(String.valueOf(questao.alternativas.get(1)));
        rbt_c.setText(String.valueOf(questao.alternativas.get(2)));
        rbt_d.setText(String.valueOf(questao.alternativas.get(3)));
        rbt_e.setText(String.valueOf(questao.alternativas.get(4)));
        
        //Limpar a Dica:
        txt_dica.setText("");
    }
    
    public void preencheDica(){
        txt_dica.setText("<html>" + questao.getDica() + "<html>");
    }
    
    public int verificaResposta() {
    int escolha = 0;

    if (rbt_a.isSelected()) {
        escolha = Integer.parseInt(rbt_a.getText());
    } else if (rbt_b.isSelected()) {
        escolha = Integer.parseInt(rbt_b.getText());
    } else if (rbt_c.isSelected()) {
        escolha = Integer.parseInt(rbt_c.getText());
    } else if (rbt_d.isSelected()) {
        escolha = Integer.parseInt(rbt_d.getText());
    } else if (rbt_e.isSelected()) {
        escolha = Integer.parseInt(rbt_e.getText());
    }

    return escolha;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Alternativas;
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton rbt_a;
    private javax.swing.JRadioButton rbt_b;
    private javax.swing.JRadioButton rbt_c;
    private javax.swing.JRadioButton rbt_d;
    private javax.swing.JRadioButton rbt_e;
    private javax.swing.JLabel txt_dica;
    private javax.swing.JLabel txt_numero;
    private javax.swing.JLabel txt_questao;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
